dataset: cifar10
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 5
- 7
- 9
- 13
- 19
- 26
- 37
- 52
- 73
fidelity_single: 5
hparams_from_file: predictor_hpo_configs/hpo_config_1.json
max_hpo_time: 0
model_metric: val_accuracy
out_dir: run
predictor: xgb
save_predictor: true
search:
  batch_size: 256
  cutout: false
  cutout_length: 16
  cutout_prob: 1.0
  data_size: 25000
  train_portion: 0.7
search_space: nasbench101
seed: 21
test_size: 100
train_size_list:
- 5
- 8
- 14
- 24
- 42
- 71
- 121
- 205
train_size_single: 700
uniform_random: 1
